## Reload a module

In [1]:
import numpy as np
import importlib
importlib.reload(np)

<module 'numpy' from '/Users/tachi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/numpy/__init__.py'>

## Import self made modules

In [2]:
import sys
sys.path.append('module path')

## Measure an elapsed time

In [3]:
import time
t0 = time.time()

for i in range(1000000):
    i ** 10

t1 = time.time()
 
# Print the elapsed time
elapsed_time = t1 - t0
print('elapsed time:', elapsed_time)

elapsed time: 0.4125809669494629


## How to use Random module

In [4]:
import random
sample_list = [i for i in range(0, 10)]

print(random.random()) # Get a float value (range is 0 to 1.0)
print(random.uniform(0, 10)) # Get a float value (range is 0 to 10 )
print(random.randint(0,10)) # Get a int value (range is 0 to 10)
print(random.choice(sample_list)) # Get a value from sample_list randomly
random.shuffle(sample_list) # shuffle sample_list
print(sample_list)

0.27362434868282703
6.599818608836817
8
0
[0, 7, 5, 9, 8, 4, 2, 6, 1, 3]


## Convert DataFrame to ndarray or list

In [5]:
import pandas as pd
x = np.linspace(0, 2 * np.pi, 10)
df = pd.DataFrame({'x': x}) # Create a DataFrame
print(type(df))

a = df.values.tolist() # To list
print(type(a))

b = df.values
c = df.as_matrix() # To ndarray
print(type(b), type(c))

<class 'pandas.core.frame.DataFrame'>
<class 'list'>
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


## Replace NaN values with arbitrary number in ndarray

In [6]:
arr = np.array([[1, 1, np.nan],[1, np.nan, 1],[1, 1, 1]])
arr[np.isnan(arr)] = 0
print(arr)

[[ 1.  1.  0.]
 [ 1.  0.  1.]
 [ 1.  1.  1.]]


## Replace NaN values with arbitrary number in DataFrame

In [7]:
df = pd.DataFrame({'data0': [1, 1, np.nan, 1, np.nan],
                   'data1': [1, 1, np.nan, 1, np.nan]})
df.fillna({'data0': 0, 'data1': 1}, inplace=True)
df

data0  data1
0    1.0    1.0
1    1.0    1.0
2    0.0    1.0
3    1.0    1.0
4    0.0    1.0

## Delete NaN values in ndarray

In [8]:
arr = np.array([[1, 1, np.nan],[1, np.nan, 1],[1, 1, 1]])
print(arr[~np.isnan(arr).any(axis=1)]) # Row
print(np.ma.compress_cols(np.ma.masked_invalid(arr))) # Column

[[ 1.  1.  1.]]
[[ 1.]
 [ 1.]
 [ 1.]]


## Delete NaN values in DataFrame

In [9]:
df = pd.DataFrame({'data0': [1, 1, np.nan, 1, np.nan],
                   'data1': [1, 1, np.nan, 1, np.nan]})
df.dropna(inplace=True)
df

data0  data1
0    1.0    1.0
1    1.0    1.0
3    1.0    1.0